### PR TITLE
Features/svg emf

### PR DESCRIPTION
**Pull request by opoudjis**

### CODE REVIEW

**Comment by CAMOBAP** [comment]
Checking windows failure...

**Comment by CAMOBAP** [comment]
@opoudjis I have reproduced the issue. I noted that if svg in current directory emf works correctly. I will check if we need to explicitly specify output emf file path

Also an interesting note, stdout/stderr 'disabled' for inkscape.exe https://wiki.inkscape.org/wiki/index.php?title=Frequently_asked_questions#I.27m_on_Windows.2C_and_command_line_parameters_don.27t_seem_to_work.21

To be updated...

**Comment by CAMOBAP** [comment]
Test cases:
 - `PWD=C:\Users\IEUser\isodoc`
     - `C:\ProgramData\chocolatey\bin\inkscape.EXE --export-type="emf" spec\assets\odf1.svg` - works
     - `C:\ProgramData\chocolatey\bin\inkscape.EXE --export-type="emf" C:\Users\IEUser\isodoc\spec\assets\odf1.svg` - works
    - `C:\ProgramData\chocolatey\bin\inkscape.EXE --export-type="emf" C:\Users\IEUser\AppData\Local\Temp\odf1.svg` - works

Previously we had an issue that temp file deleted earlier than `system ...` called, checking...

**Comment by CAMOBAP** [comment]
The root of the issue: for some reason `inkscape.exe` was selected instead of `inkscape.com`. inkscape.exe 'exists' earlier than processing done. I have added `sleep 5` after `system ...` call and all tests passed

Still trying to figure out why inkscape.com don't called...

UPD. `choco install -y inkscape` don't install `inkscape.com`, only `inkscape.exe`, 

@opoudjis this is a complete infrastructure/environment issue, so once CI will install 'correct' Inkscape, no extra changes in the code will be needed. I will continue research how to accomplish this

**Comment by CAMOBAP** [comment]
https://github.com/chocolatey-community/chocolatey-coreteampackages/issues/1717 - reported to provide `inkscape.com` alongside with `inkscape.exe`

I will add tiny commit to support execution commands with space in the path, working on workaround to install inkscape.com

**Comment by CAMOBAP** [comment]
@opoudjis one test still left on CI (works for me locally)

```
...
              <image src='action_schemaexpg1.svg' id='_' mimetype='image/svg+xml' height='auto' width='auto'>
       -        <emf src='./action_schemaexpg1.emf'/>
       +        <emf src='.\action_schemaexpg1.emf'/>
              </image>
            </figure>
            <figure id='_'>
              <image src='action_schemaexpg2.svg' id='_' mimetype='image/svg+xml' height='auto' width='auto' alt='Workmap'>
       -        <emf src='./action_schemaexpg2.emf'/>
       +        <emf src='.\action_schemaexpg2.emf'/>
...
```

I'm not sure what is right fix here, could you please have a look?

**Comment by ronaldtse** [comment]
@CAMOBAP @opoudjis re: path slash: we probably have to normalise the path slash to a Unix-style slash when writing Metanorma XML, and when we read the path we have to read it using Ruby's File/Pathname that normalises the slash.

**Pull request merged**
