### PR TITLE
Vectory

### PR DESCRIPTION
**Pull request by alexeymorozov**
Closes https://github.com/metanorma/isodoc/issues/553

### Metanorma PR checklist

 - [ ] Breaking changes (list related PRs)
 - [ ] Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
 - [ ] Gem with native library introduced

### CODE REVIEW

**Comment by opoudjis** [comment]
@alexeymorozov The error in spec is simply an expectation that if Inkspace is not installed, SVGs cannot be converted to EMF, which is no longer applicable now that vectory exists; so you can simply remove that test from spec/isodoc/figures_spec.rb line 705.

**Review by opoudjis — APPROVED** [review]

**Comment by ronaldtse** [comment]
@opoudjis please merge after approval. I’ll merge this this time. Thanks.

**Comment by opoudjis** [comment]
Wanted to give you the chance to comment.

**Comment by ronaldtse** [comment]
Thanks, I’ll definitely comment if I have to even after merging :-)

**Pull request merged**
